language: node_js
node_js:
  - '6'
  - '8'
  - 'stable'

sudo: required
dist: trusty

script: npm run test:ci

before_install: npm install -g greenkeeper-lockfile@1
before_script: 
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload
